### ISSUE TITLE
No address associated with hostname

### ISSUE THREAD

**Issue by 2Wanderer** [hcpy2-0/hcpy#111]
Hi, i have installed the HA-addon, configured it and started it. 

Here's a snippet of the logs: 

`LastProgram', '1': 'EcoAsDefault'}}, '4356': {'name': 'Dishcare.Dishwasher.Setting.ExtraDry', 'access': 'readWrite', 'available': 'true', 'refCID': '01', 'refDID': '00'}, '4357': {'name': 'Dishcare.Dishwasher.Setting.HotWater', 'access': 'readWrite', 'available': 'true', 'refCID': '03', 'refDID': '80', 'values': {'0': 'ColdWater', '1': 'HotWater'}}, '4378': {'name': 'Dishcare.Dishwasher.Setting.InfoLight', 'access': 'readWrite', 'available': 'true', 'refCID': '01', 'refDID': '00'}, '4354': {'name': 'Dishcare.Dishwasher.Setting.RinseAid', 'access': 'readWrite', 'available': 'true', 'refCID': '03', 'refDID': '80', 'values': {'0': 'Off', '1': 'R01', '2': 'R02', '3': 'R03', '4': 'R04', '5': 'R05', '6': 'R06'}}, '4355': {'name': 'Dishcare.Dishwasher.Setting.SensitivityTurbidity', 'access': 'readWrite', 'available': 'true', 'refCID': '03', 'refDID': '80', 'values': {'0': 'Standard', '1': 'Sensitive', '2': 'VerySensitive'}}, '4382': {'name': 'Dishcare.Dishwasher.Setting.SilenceOnDemandDefaultTime', 'access': 'readWrite', 'available': 'true', 'max': '1800', 'min': '60', 'refCID': '10', 'refDID': '82', 'stepSize': '60', 'discovery': {'payload_values': {'unit_of_measurement': 's', 'device_class': 'duration'}}}, '4364': {'name': 'Dishcare.Dishwasher.Setting.SoundLevelSignal', 'access': 'readWrite', 'available': 'true', 'refCID': '03', 'refDID': '80', 'values': {'0': 'Off', '1': 'Low', '2': 'Medium', '3': 'High'}}, '4384': {'name': 'Dishcare.Dishwasher.Setting.SpeedOnDemand', 'access': 'read', 'available': 'true', 'refCID': '01', 'refDID': '00', 'discovery': {'component_type': 'binary_sensor', 'payload_values': {'payload_on': True, 'payload_off': False}}}, '4367': {'name': 'Dishcare.Dishwasher.Setting.WaterHardness', 'access': 'readWrite', 'available': 'true', 'refCID': '03', 'refDID': '80', 'values': {'0': 'H00', '1': 'H01', '2': 'H02', '3': 'H03', '4': 'H04', '5': 'H05', '6': 'H06', '7': 'H07'}}, '4103': {'name': 'Dishcare.Dishwasher.Status.EcoDryActive', 'access': 'read', 'available': 'true', 'refCID': '01', 'refDID': '00', 'discovery': {'component_type': 'binary_sensor', 'payload_values': {'payload_on': True, 'payload_off': False}}}, '4096': {'name': 'Dishcare.Dishwasher.Status.ProgramPhase', 'access': 'read', 'available': 'true', 'refCID': '03', 'refDID': '80', 'values': {'0': 'None', '1': 'PreRinse', '2': 'MainWash', '3': 'FinalRinse', '4': 'Drying'}}, '4101': {'name': 'Dishcare.Dishwasher.Status.SilenceOnDemandRemainingTime', 'access': 'read', 'available': 'true', 'refCID': '10', 'refDID': '82', 'discovery': {'payload_values': {'unit_of_measurement': 's', 'device_class': 'duration'}}}}}
Hello devices_file='/config/devices.json' mqtt_host='redacted' mqtt_prefix='homeconnect/' mqtt_port=1883 mqtt_username='mqtt' mqtt_password='redacted' mqtt_ssl=False mqtt_cafile=None mqtt_certfile=None mqtt_keyfile=None mqtt_clientname='hcpy1'domain_suffix='' debug=False ha_discovery=True
2024-11-30 12:16:43.552568 MQTT connection established: 0
2024-11-30 12:16:43.552901 dishwasher set topic: homeconnect/dishwasher/set
2024-11-30 12:16:43.553136 dishwasher program topic: homeconnect/dishwasher/activeProgram
2024-11-30 12:16:43.553301 dishwasher program topic: homeconnect/dishwasher/selectedProgram
2024-11-30 12:16:50.560106 dishwasher ERROR [Errno -5] No address associated with hostname
2024-11-30 12:17:54.396328 dishwasher ERROR [Errno -5] No address associated with hostname
2024-11-30 12:18:58.146870 dishwasher ERROR [Errno -5] No address associated with hostname
2024-11-30 12:20:01.896930 dishwasher ERROR [Errno -5] No address associated with hostname
2024-11-30 12:21:05.646888 dishwasher ERROR [Errno -5] No address associated with hostname
2024-11-30 12:22:09.647096 dishwasher ERROR [Errno -5] No address associated with hostname
2024-11-30 12:23:13.396982 dishwasher ERROR [Errno -5] No address associated with hostname`

So i got the 'No address associated with hostname error' The mqtt sensors are added in HA but are not updated. Is it the hostname of the dishwasher it cannot resolve? and maybe you can guide me a little to troubleshoot this issue?

**Comment by Meatballs1** [comment]
The domain suffix in the options can help, if you need to add .local or whatever your local DNS suffix is.

If that doesn't work you can modify the devices.json and change the hostname to something that does resolve, or use an IP (but you will likely want to ensure you have a static DHCP lease for the device if you take that route).

**Comment by 2Wanderer** [comment]
Ah thxs! however i'm running the ha-addon. By my knowlegde i can't exec into the container or make persistent volume mappings to the host or the HA container itself  (RPI supervised) can you maybe add this mapping? So we can change the value's within the configfolder within HA? or is there a more convienent way to do this?

**Comment by saveriol** [comment]
The [addon_config](https://developers.home-assistant.io/docs/add-ons/configuration/#add-on-advanced-options) share is mapped so you'll find devices.json there

**Comment by 2Wanderer** [comment]
thankyou! didn't know that fixed. It's working now :)

**Comment by 2Wanderer** [comment]
closed

**Comment by cibernox** [comment]
Note for future visitors:

I was getting this same error so I hardcoded the IP address of my devices as `host` on the devices.json and it worked. 
All my devices have static IP addresses defined in my router, so it should be fine.

**Comment by Mwalton4uk** [comment]
> Note for future visitors:
> 
> I was getting this same error so I hardcoded the IP address of my devices as `host` on the devices.json and it worked. All my devices have static IP addresses defined in my router, so it should be fine.

whats the code for this sorry?

**Comment by cibernox** [comment]
@Mwalton4uk 
Edit the `devices.json` file and put something like:
```
[
    {
        "name": "dishwasher",
        "host": "192.168.20.173", // <------------ fixed IP
        "key": "some key",
        "description": { /* ... */ },
        "features": { /* ... */ }
  },
    {
        "name": "oven",
        "host": "192.168.20.174", // <------------ fixed IP
        "key": "some key",
        "description": { /* ... */ },
        "features": { /* ... */ }
  },
]
```
