### ISSUE TITLE
washer updates are not received anymore

### ISSUE THREAD

**Issue by bartsnijder** [hcpy2-0/hcpy#40]
The washer is running and gives feedback to terminal
washer {'ProgramProgress': 22, 'RemainingProgramTime': 4260}

No data is sent to mqtt broker however.
The initial state @ washer connect is properly send to broker

**Comment by Meatballs1** [comment]
@bartsnijder I think https://github.com/hcpy2-0/hcpy/pull/36 should cause these to update. Did it work on a previous version/original? This is the first weekend I've been running it properly.

**Comment by bartsnijder** [comment]
@Meatballs1 yes, they did work before (but I guess a possible root cause was meanwhile found in  #36 )

**Comment by Meatballs1** [comment]
Was that on the osresearch original repo or the fork you were using?

**Comment by bartsnijder** [comment]
As far as I can look back in available history, latest versions of hcpy that I used and reported remaining time seem indeed to be from bruestel and osresearch. Sorry for the confusion

**Comment by Meatballs1** [comment]
I think all changes are merged now so this data should all be received. If you want to test the latest?

**Comment by bartsnijder** [comment]
Not tested extensively yet (1 wash operation) but all seems to work as expected! Will keep on monitoring the performance coming weeks. Great update, very much appreciated. Thanks for all effort!
