### ISSUE TITLE
DNS issues in HA Addon

### ISSUE THREAD

**Issue by Meatballs1** [hcpy2-0/hcpy#55]
If you look at the DNS logs on the HAOS console the names it is trying to resolve are all appended with `.local.hass.io`

**Comment by Meatballs1** [comment]
So the /etc/resolve.conf contains `search local.hass.io`.

Removing this and restarting the container works. Not sure if it will be updated when DHCP reloads in the container?

This is presumably being set by DHCP/docker configuration settings in HAOS.

**Comment by Meatballs1** [comment]
https://github.com/home-assistant/plugin-dns/issues/118

There is also another issue about it not working with mDNS either

**Comment by Meatballs1** [comment]
Potential workarounds:

* ha-login.py adds .local or dns suffix to the hostnames
* hcsocket catches exception and retries with .local?

**Comment by pmagyar** [comment]
I have done some research:
1. i think mdns in HomeAssistant ist working. I have checked it with:
```
root@:~# ha dns info
fallback: true
host: 172.30.32.3
llmnr: true
locals:
- dns://192.168.178.1
mdns: true
servers: []
update_available: false
version: 2024.04.0
version_latest: 2024.04.0
```

2. but only the fqdn ist working in the container:
```
root@4790c40a-hcpy:/app# host siemens-dishwasher
root@4790c40a-hcpy:/app# host siemens-dishwasher.fritz.box
siemens-dishwasher.fritz.box has address 192.168.178.28
root@4790c40a-hcpy:/app# host siemens-dishwasher.local
Host siemens-dishwasher.local not found: 2(SERVFAIL)
root@4790c40a-hcpy:/app#
```

3. I looked at other addons. For example the MQTT Browser Addon https://github.com/GollumDom/addon-repository
With this addon, i have the same issue. Only the ip or the fqdn works as Host....

4. the issues that you found are interesting. I have found another one https://github.com/home-assistant/plugin-dns/pull/86 

I think currently it is not possible with homeassistant ( ... or i have a bug in my setup....).
Anyway, i think at first the workaround "ha-login.py adds .local or dns suffix to the hostnames" sounds good. 
    - Maybe we should create a parameter e.g. "--dns-tld" where everyone can add his own tld (?)
