### ISSUE TITLE
Per device LWT not retained?

### ISSUE THREAD

**Issue by noxhirsch** [hcpy2-0/hcpy#57]
For some reason my device LWTs are missing the retain flag in my setup.

I realized that when I thought, `availability_mode` should be `all` instead of `latest`. Otherwise it can happen that a device goes offline - then HC2MQTT goes offline and online again - and then HA thinks that the device is online again because the last update comes from HC2MQTTs LWT.  With `availability_mode: all`, the device is only availible in HA, when HC2MQTTs LWT *and* the devices LWT are online. Or am I misunderstanding something?

`availability_mode: all` does not currently work, because the device LWT is only `online` for a short time. But as far as I understand https://github.com/hcpy2-0/hcpy/pull/41, it should be retained?!
<img width="397" alt="image" src="https://github.com/hcpy2-0/hcpy/assets/30938717/68dfb856-9be6-457a-a1d4-f90d349bc509">
<img width="395" alt="image" src="https://github.com/hcpy2-0/hcpy/assets/30938717/569b2b33-6106-4af5-8f20-5f4d5effdbd5">

**Comment by Meatballs1** [comment]
I think `all` with both messages being retained probably would work better. Will give it a test.

**Comment by Meatballs1** [comment]
`all` seems to work good for me, will update the documentation
