### ISSUE TITLE
Cannot start hcpy as docker

### ISSUE THREAD

**Issue by bartsnijder** [hcpy2-0/hcpy#75]
I'm trying to start HCPY as a docker with "docker compose up"
When the docker is build and run it logs the error that it cannot connect ""

> app-1  |   File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
app-1  |     raise err
app-1  |   File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
app-1  |     sock.connect(sa)
app-1  | ConnectionRefusedError: [Errno 111] Connection refused

Any idea what I do wrong?

**Comment by Meatballs1** [comment]
Suspect that means it can't connect to the configured MQTT server.

**Comment by bartsnijder** [comment]
Indeed, the "localhost" does not work as MQTT broker address in Docker. Entering the local IP address solves it.
Thanks!
