### ISSUE TITLE
Communication problems with current servers?

### ISSUE THREAD

**Issue by mobrembski** [hcpy2-0/hcpy#81]
Hi! :)

Thanks for this great project!.

I had a question, response from my hc-login script is always bad username:

`Wrong credentials.
If you forgot your login/password, you can restore them by opening https://singlekey-id.com/auth/en-us/login in browser
`

Even if i type in correct password and checked on that page. 
Is it possible something has changed, or this script works only in certain locations (possibly in US only?)

**Comment by Meatballs1** [comment]
I think most users are in EU, we had a pull request for US servers recently, so that should work, but maybe hit different endpoints if you are in a different region?

It's possible they have changed the login process, and we wouldn't see that as it only needs to be called once. Will need to find some time to check

**Comment by mobrembski** [comment]
I;ve digged this problem i dont think its related to geolocation. Unfortunately Home Connect changed its login procedure some time ago.

So comparing to other HomeAssistant component - https://github.com/ekutner/home-connect-hass/tree/master - It looks like
1) User has to enter login and password
2) Home Connect servers responds with URL to open in web browser and type in again login and password
3) After sucessfull login, web page responds with "Now return to application".
4) Application does something with it i guess, not really famillar with OAuth.

Current code is not aware of 2 point. Servers responds with url to login page but it thinks its a wrong password state

**Comment by mobrembski** [comment]
I have a look at possible scopes for login here:
https://api-docs.home-connect.com/authorization/#authorization-scopes

Unfortunately, only     "IdentifyAppliance", "Monitor", "Control" and "Settings" are allowed.
This means that reading account is not possible. 

However i wonder if IndentifyAppliance is not enoqugh.

**Comment by drbiosignals** [comment]
Which python version do you use?

**Comment by Meatballs1** [comment]
I've just retried the hc-login.py  and its still working for me. The home-connect-hass is using  the public  API so likely  has a different authentication  flow  than the mobile app (which hc-login mimics).

If you've got  special characters etc have you made sure the password  is passed correctly on the command line? e.g. try single quotes `'MySecretPassword!£$$'

**Comment by mobrembski** [comment]
> I've just retried the hc-login.py and its still working for me. The home-connect-hass is using the public API so likely has a different authentication flow than the mobile app (which hc-login mimics).
> 
> If you've got special characters etc have you made sure the password is passed correctly on the command line? e.g. try single quotes `'MySecretPassword!£$$'`

YES! That was it! Quotes are needed if special characters are in password!

Thank you very much!
