### ISSUE TITLE
Domain part in "host" breaks MQTT utodiscovery in HA

### ISSUE THREAD

**Issue by elronzo** [hcpy2-0/hcpy#91]
Due to my network configuration I do need a FQDN instead of a shortname. But when I alter 

"host": "BOSCH-Dryer-somenumber"

to 

"host": "BOSCH-Dryer-somenumber.lan"

MQTT autodiscovery won't work anymore because of the dot in the senor's name.

**Comment by saveriol** [comment]
There's a PR for this: #89

**Comment by elronzo** [comment]
Perfect. So I don't even need to fiddle around in the code myself!
